### ISSUE TITLE
Watson Translate Action fails due to SDK change.

### ISSUE THREAD

**Issue by jthomas** [openwhisk/openwhisk#1022]
## Environment details:

Bluemix

## Steps to reproduce the issue:

1.   wsk action invoke --result -b /whisk.system/watson/translate -p translateFrom english -p translateTo german -p payload "Hello, my name is James" -p username $USERNAME -p password $PASSWORD

## Provide the actual results and outputs:

```
{
    "logs": [
        "2016-08-08T15:57:23.205906573Z stdout: params: { translateTo: 'german',",
        "2016-08-08T15:57:23.205956052Z stdout: payload: 'Hello, my name is James',",
        "2016-08-08T15:57:23.205974056Z stdout: username: 'xxx',",
        "2016-08-08T15:57:23.205985528Z stdout: translateFrom: 'english',",
        "2016-08-08T15:57:23.205996002Z stdout: password: 'yyy' }",
        "2016-08-08T15:57:23.206338972Z stderr: Error: Watson language_translation is now language_translator. Set {silent: true} to disable this message.",
        "2016-08-08T15:57:23.206355522Z stderr: at Object.defineProperty.value (/nodejsAction/node_modules/watson-developer-cloud/lib/index.js:302:20)",
        "2016-08-08T15:57:23.206365322Z stderr: at doTranslateTexts (eval at NodeActionRunner (/nodejsAction/runner.js:32:21), <anonymous>:89:39)",
        "2016-08-08T15:57:23.206376944Z stderr: at NodeActionRunner.main [as userScriptMain] (eval at NodeActionRunner (/nodejsAction/runner.js:32:21), <anonymous>:24:5)",
        "2016-08-08T15:57:23.206387358Z stderr: at NodeActionRunner.run (/nodejsAction/runner.js:71:27)",
        "2016-08-08T15:57:23.206402041Z stderr: at doRun (/nodejsAction/src/service.js:148:24)",
        "2016-08-08T15:57:23.206411751Z stderr: at runCode (/nodejsAction/src/service.js:92:13)",
        "2016-08-08T15:57:23.206425961Z stderr: at safeEndpoint (/nodejsAction/app.js:57:13)",
        "2016-08-08T15:57:23.206436477Z stderr: at Layer.handle [as handle_request] (/nodejsAction/node_modules/express/lib/router/layer.js:95:5)",
        "2016-08-08T15:57:23.206446991Z stderr: at next (/nodejsAction/node_modules/express/lib/router/route.js:131:13)",
        "2016-08-08T15:57:23.206457115Z stderr: at Route.dispatch (/nodejsAction/node_modules/express/lib/router/route.js:112:3)",
        "2016-08-08T15:57:23.71799997Z  stdout: error: { error_code: 404,",
        "2016-08-08T15:57:23.718037388Z stdout: error_message: 'cannot find service matching the request data' }",
        "2016-08-08T15:57:23.72126162Z  stdout: output: {}"
    ],
    "response": {
        "result": {
            "error": {
                "error_code": 404,
                "error_message": "cannot find service matching the request data"
            }
        },
        "status": "application error",
        "success": false
    }, ...
}
```

**Comment by jasonpet** [comment]
I will handle this once we update our watson-developer-cloud npm package to 2.x.  Right now we are using 1.12.4 for our nodejs6 container.  In 1.12.4 the API is still language_translation and not language_translator.

**Comment by jthomas** [comment]
User error, I should have read the docs.
https://github.com/openwhisk/openwhisk/blob/master/docs/catalog.md#translating-text
