### ISSUE TITLE
limits.ThrottleTests is not running in a stable way

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#1196]
I kept on receiving this error from time to time from the result of the travis ci build for my PRs. It fails many times, but sometimes it may pass.

```
limits.ThrottleTests > Throttles should throttle multiple invokes of one action FAILED
    org.scalatest.exceptions.TestFailedException: 0 was not greater than 0
        at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
        at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6231)
        at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6265)
        at limits.ThrottleTests$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ThrottleTests.scala:143)
        at limits.ThrottleTests$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ThrottleTests.scala:130)
        at common.WskTestHelpers$class.withAssetCleaner(WskTestHelpers.scala:66)
        at limits.ThrottleTests.withAssetCleaner(ThrottleTests.scala:43)
        at limits.ThrottleTests$$anonfun$1.apply$mcV$sp(ThrottleTests.scala:129)
        at limits.ThrottleTests$$anonfun$1.apply(ThrottleTests.scala:129)
        at limits.ThrottleTests$$anonfun$1.apply(ThrottleTests.scala:129)
        at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
        at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
        at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
        at org.scalatest.Transformer.apply(Transformer.scala:22)
        at org.scalatest.Transformer.apply(Transformer.scala:20)
        at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647)
        at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
        at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1683)
        at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1644)
        at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
        at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
        at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
        at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1656)
        at limits.ThrottleTests.org$scalatest$BeforeAndAfterEachTestData$$super$runTest(ThrottleTests.scala:43)
        at org.scalatest.BeforeAndAfterEachTestData$class.runTest(BeforeAndAfterEachTestData.scala:193)
        at limits.ThrottleTests.runTest(ThrottleTests.scala:43)
        at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
        at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
        at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
        at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1714)
        at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1683)
        at org.scalatest.Suite$class.run(Suite.scala:1424)
        at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1683)
        at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
        at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
        at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
        at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1760)
        at limits.ThrottleTests.org$scalatest$BeforeAndAfterAll$$super$run(ThrottleTests.scala:43)
        at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
        at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
        at limits.ThrottleTests.run(ThrottleTests.scala:43)
```

**Comment by rabbah** [comment]
@cbickel with recent tweaks to the container pool the variables in this test may need some further tweaking.

**Comment by rabbah** [comment]
@cbickel going to take a look at this.

**Comment by dubeejw** [comment]
We are still seeing this test failure.

**Comment by mdeuser** [comment]
Related PG incidents for 15 Sept 2016:
https://bluemix.pagerduty.com/incidents/PYG0C2S
https://bluemix.pagerduty.com/incidents/PU7I3ZI

**Comment by perryibm** [comment]
This should be fixed by now.  Let's reopen this if it recurs but the limits and throttle tests have both been redone.  There is a small risk this will still happen as a result of consul getting bogged down but this should also get fixed soon.
