### ISSUE TITLE
deploy failed

### ISSUE THREAD

**Issue by lzbj** [openwhisk/openwhisk#152]
Hi,

I succcessfully build the openwhisk docker images according to READme, but when I try ant deploy, I got the following error.

```
he ' characters around the executable and arguments are
not part of the command.
     [exec] The invoker hosts are [(0, '172.17.0.1', False)]
     [exec] Removing invoker0        at 172.17.0.1:4243     0.0 sec   did nothing
     [exec] Skipping pull
     [exec] Starting invoker0        at 172.17.0.1:4243     0.4 sec   SUCCEEDED
     [exec] Container 6918e6898fab8349 at 172.17.0.1:4243     0.1 sec   SUCCEEDED
     [exec]   has imageId   fb184548770d4b3bbe6647f26d1e7a7f84b76fd11a562a802978fe801368fcdf
     [exec] Checking invoker0                                               63.3 sec   FAILED
     [exec] return code = 7 
     [exec] 172.17.0.1:12001
     [exec] invoker0 is not responding
     [exec] 
     [exec] Tried to deploy 1 invokers. Failed to process 1 invokers in 63.8 sec.
  [antcall] Exiting /home/vagrant/openwhisk/core/build.xml.
      [ant] Exiting /home/vagrant/openwhisk/core/build.xml.

BUILD FAILED
/home/vagrant/openwhisk/build.xml:51: The following error occurred while executing this line:
/home/vagrant/openwhisk/core/build.xml:14: The following error occurred while executing this line:
/home/vagrant/openwhisk/core/build.xml:26: exec returned: 1
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:643)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Parallel$TaskRunnable.run(Parallel.java:453)
        at java.lang.Thread.run(Thread.java:745)
```

what might be the issue, is any anyone else encountered the same issue?

Thanks
dliu

**Comment by rabbah** [comment]
You have a valid couch or cloudant configuration file?

**Comment by lzbj** [comment]
thank you rabbah for your quick response, I'll check it.

**Comment by rabbah** [comment]
Is this still an issue?

**Comment by sjfink** [comment]
this seems like a common-ish failure pattern -- I suggest we start a "Troubleshooting" doc, starting with this failure symptom.

**Comment by AnanthaKrishnanKG** [comment]
Hi , I am facing the same issue while deploying openwhisk in local setup. I tried almost everything... I reinstalled docker... tried `ant clean`, `ant redeploy` everything.... Still the same error.. Can anyone please help me ??... 
<img width="946" alt="screen shot 2016-05-19 at 12 46 23 pm" src="https://cloud.githubusercontent.com/assets/10846524/15401353/c9272596-1e0c-11e6-9f4f-b52bf8d4ca36.png">
<img width="1280" alt="screen shot 2016-05-19 at 9 58 42 pm" src="https://cloud.githubusercontent.com/assets/10846524/15401371/df6ba82c-1e0c-11e6-80cc-90c91b2f7473.png">

**Comment by rabbah** [comment]
I reached out to you directly to help you investigate the issue.

**Comment by lzbj** [comment]
@AnanthaKrishnanKG, I remember initially I wanted to use a immoral DB, then I changed the DB service to cloudant DB service, and changed my whisk.properties file accordingly.
db.provider=Cloudant
db.prefix=vagrant_vincentdemwsk_
db.whisk.actions=vagrant_vincentdemwsk_whisks
db.whisk.auths=subjects
db.host=dliu.cloudant.com
db.port=443
db.username=dliu
db.password=your_password
But your could try your local couchDB deploy, there is a good doc just for your reference.
https://developer.ibm.com/open/2016/05/23/setup-openwhisk-use-local-couchdb/

**Comment by AnanthaKrishnanKG** [comment]
@lzbj  Ok I will try that.. @rabbah I replied to that mail..

**Comment by AnanthaKrishnanKG** [comment]
@lzbj .. I am also using the cloudant..

db.provider=Cloudant
db.protocol=https
db.host=myusrname.cloudant.com
db.port=443
db.username=myuserame
db.password=mypassword
db.prefix=vagrant_ananthasmwsk_
db.whisk.actions=vagrant_ananthasmwsk_whisks
db.whisk.auths=subjects


It seems fine.. and I checked my cloudant.. It created a db there...

**Comment by AnanthaKrish** [comment]
Please send comments to this one

**Comment by AnanthaKrish** [comment]
I got the issue again

[invoker0_logs.log.zip](https://github.com/openwhisk/openwhisk/files/279291/invoker0_logs.log.zip)

**Comment by perryibm** [comment]
@rabbah The bug could be that the invoker came up too slowly.  If you look at the log, you see that the second time, it took 10 seconds for it to come up.  The invoker lifecycle PR 495 will help with that.  Another thing is to increase the allowed check time because a local deploy on a loaded machine might just take longer.

```
[2016-05-24T10:45:13.992Z] [INFO] Slf4jLogger started [akka.event.slf4j.Slf4jLogger:80] 
[2016-05-24T10:45:38.660Z] [INFO] Slf4jLogger started [akka.event.slf4j.Slf4jLogger:80] 
[2016-05-24T10:45:39.672Z] [INFO] [#sid_101] [WhiskContainer] [marker:invoker_docker.run_start:7927] runDockerCmd: transid = #sid_101
[2016-05-24T10:45:39.661Z] [INFO] [#sid_100] [ContainerPool] [marker:invoker_docker.ps_start:7916] runDockerCmd: transid = #sid_100
[2016-05-24T10:45:42.837Z] [INFO] [#sid_100] [ContainerPool] [marker:invoker_docker.ps_finish:11092] 
[2016-05-24T10:45:42.991Z] [INFO] [??] [SimpleExec] Done running command: hostname -f
[2016-05-24T10:45:43.869Z] [INFO] Slf4jLogger started [akka.event.slf4j.Slf4jLogger:80] 
[2016-05-24T10:45:44.963Z] [INFO] [#sid_101] [SimpleExec] Done running command: /usr/bin/docker --host tcp://172.17.0.1:4243 run -e EDGE_HOST=172.17.0.1:443 -e WHISK_VERSION_NAME=local:2016-05-24T10:39:58+00:00 -e SERVICE_IGNORE=true --name wsk0_1_warmJsContainer_20160524T104539624Z -m 256m --cap-drop NET_RAW --cap-drop NET_ADMIN --ulimit nofile=64:64 --ulimit nproc=512:512 --net bridge -d whisk/nodejsaction
[2016-05-24T10:45:44.963Z] [INFO] [#sid_101] [WhiskContainer] [marker:invoker_docker.run_finish:13218] 
[2016-05-24T10:45:45.334Z] [INFO] [#sid_101] [WhiskContainer] [marker:invoker_docker.inspect_start:13589] runDockerCmd: transid = #sid_101
[2016-05-24T10:45:45.408Z] [INFO] [#sid_101] [SimpleExec] Running command: /usr/bin/docker --host tcp://172.17.0.1:4243 inspect --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' wsk0_1_warmJsContainer_20160524T104539624Z
[2016-05-24T10:45:46.026Z] [INFO] [#sid_101] [SimpleExec] Done running command: /usr/bin/docker --host tcp://172.17.0.1:4243 inspect --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' wsk0_1_warmJsContainer_20160524T104539624Z
[2016-05-24T10:45:46.027Z] [INFO] [#sid_101] [WhiskContainer] [marker:invoker_docker.inspect_finish:14282] 
[2016-05-24T10:45:46.033Z] [INFO] [#sid_101] [WhiskContainer] [marker:invoker_docker.pause_start:14288] runDockerCmd: transid = #sid_101
[2016-05-24T10:45:46.033Z] [INFO] [#sid_101] [SimpleExec] Running command: /usr/bin/docker --host tcp://172.17.0.1:4243 pause 9cfff28f875d500ef3459e8c6abbbd400a736f3418fb6477af6151bc09dac242
[2016-05-24T10:45:47.206Z] [INFO] Bound to /0.0.0.0:8080 [spray.can.server.HttpListener:74] 
```

**Comment by rabbah** [comment]
@AnanthaKrish I just merged a pull request from @perryibm that should improve the behavior for you. Can you rebase to head and try again?

**Comment by AnanthaKrish** [comment]
can I merge the latest Master code to my local openwhisk code ?

**Comment by rabbah** [comment]
> git remote add upstream git@github.com:openwhisk/openwhisk
> git fetch --all
> git rebase upstream/master

**Comment by rabbah** [comment]
@lzbj do you still have this problem? If not can we close?
