### ISSUE TITLE
Document pip pre-req/version for troubleshooting

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk#290]
Error I get is:

```
whisky@openwhisk:~$ sudo pip install --upgrade https://new-console.ng.bluemix.net/openwhisk/cli/download
Downloading/unpacking https://new-console.ng.bluemix.net/openwhisk/cli/download
Downloading download (unknown size): 19kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
  status = self.run(options, args)
File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
  requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
  do_download,
File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
  self.session,
File "/usr/lib/python2.7/dist-packages/pip/download.py", line 582, in unpack_http_url
  unpack_file(temp_location, location, content_type, link)
File "/usr/lib/python2.7/dist-packages/pip/util.py", line 643, in unpack_file
  untar_file(filename, location)
File "/usr/lib/python2.7/dist-packages/pip/util.py", line 561, in untar_file
  tar = tarfile.open(filename, mode)
File "/usr/lib/python2.7/tarfile.py", line 1678, in open
  return func(name, filemode, fileobj, **kwargs)
File "/usr/lib/python2.7/tarfile.py", line 1727, in gzopen
  **kwargs)
File "/usr/lib/python2.7/tarfile.py", line 1705, in taropen
  return cls(name, mode, fileobj, **kwargs)
File "/usr/lib/python2.7/tarfile.py", line 1574, in __init__
  self.firstmember = self.next()
File "/usr/lib/python2.7/tarfile.py", line 2335, in next
  raise ReadError(str(e))
ReadError: invalid header

Storing debug log for failure in /home/whisky/.pip/pip.log
```

**Comment by nauerz-ibm** [comment]
Here is what it fixed it for me:

```
$ sudo python -m pip install --upgrade --force setuptools
$ sudo python -m pip install --upgrade --force pip
```

**Comment by rabbah** [comment]
This issue is not specific to openwhisk. We don't document how to upgrade the CLI from an external source. We are transitioning to a go CLI in #238 and I am inclined to close this as won't fix in openwhisk.

@starpit perhaps a troubleshooting tip is useful in CLI configuration page from the UI.

**Comment by nauerz-ibm** [comment]
I am fine with closing as this indeed seems to be a python/pip related thing; I found the answer on stackoverflow where people ended-up in similar scenarios not having anything to do with OW at all.
